import type { Metadata } from "next";
import { poppins } from './fonts';
import "./globals.css";
import UserNavBar from './components/NavBar';
import AuthProvider from '@/provider/authProvider'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-white`} >
        <AuthProvider>
          <UserNavBar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
